# Generated by Django 4.2.1 on 2023-11-14 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='check_in_date must be greater than or equal to today',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('check_in_date__gte', datetime.datetime(2023, 11, 14, 6, 56, 13, 641832, tzinfo=datetime.timezone.utc))), name='check_in_date must be greater than or equal to today'),
        ),
    ]
