# Generated by Django 4.2.1 on 2023-11-15 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_transcation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='check_in_date must be greater than or equal to today',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('check_in_date__gte', datetime.datetime(2023, 11, 15, 13, 27, 57, 847785, tzinfo=datetime.timezone.utc))), name='check_in_date must be greater than or equal to today'),
        ),
    ]
