# Generated by Django 4.2.1 on 2023-11-15 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_check_in_date_must_be_greater_than_or_equal_to_today_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='check_in_date must be greater than or equal to today',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('check_in_date__gte', datetime.datetime(2023, 11, 15, 15, 14, 56, 912903, tzinfo=datetime.timezone.utc))), name='check_in_date must be greater than or equal to today'),
        ),
    ]
