# Generated by Django 4.2.1 on 2023-12-02 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Resort', 'Resort')], max_length=50)),
                ('total_rooms', models.PositiveIntegerField()),
                ('single_room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adults_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('property_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('parking', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('room_description', models.TextField()),
                ('property_name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('maplocation', models.CharField(max_length=110)),
                ('is_verified', models.BooleanField(default=False)),
                ('country', models.CharField(default='INDIA', max_length=100)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='room_photos/')),
                ('room_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='partner.roomproperty')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1_star', '1 Star'), ('3_star', '3 Stars'), ('4_star', '4 Stars'), ('deluxe_premium_luxury', 'Deluxe/Premium/Luxury')], max_length=50)),
                ('room_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='partner.roomproperty')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(choices=[('power_backup', 'Power Backup'), ('ac', 'AC'), ('fire_extinguisher', 'Fire Extinguisher'), ('wifi', 'WiFi'), ('daily_house_keeping', 'Daily House Keeping'), ('attached_bathroom', 'Attached Bathroom'), ('first_aid_kit', 'First Aid Kit'), ('tv', 'TV'), ('air_conditioner', 'Air Conditioner')], max_length=50)),
                ('room_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='partner.roomproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Blockbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bloking', to='partner.roomproperty')),
            ],
        ),
    ]
